using LandonApi.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;

namespace LandonApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    //add api version

    public class InfoController:ControllerBase
    {
        private readonly HotelInfo _hotelInfo;
        //inject ioption and get hotel info using i option
        public InfoController(IOptions<HotelInfo> hotelInfoWrapper)
        {
            _hotelInfo = hotelInfoWrapper.Value;
        }
        //set action support http type and action name
        [HttpGet(Name =nameof(GetInfo))]
        /*
            Because there are multiple return types and paths in this type of action,
            liberal use of the [ProducesResponseType] attribute is necessary. 
            This attribute produces more descriptive response details 
            for web API help pages generated by tools like Swagger
        */
        [ProducesResponseType(200)]
        public ActionResult<HotelInfo> GetInfo()
        {
            _hotelInfo.Href = Url.Link(nameof(GetInfo), null);

            return _hotelInfo;
        }
    }
}
